dnn_configuration:
  architecture: 
    input_dim: 46
    hidden_1_size: 32
    hidden_2_size: 32
    dropout_rate: 0.2 
    output_dim: 2
  training:
    batch_size: 64
    epochs: 25
    learning_rate: 0.0001
